# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OnBoLluXgBhWsNDmZ7gYMz6nIap0QjL-

Funções
"""

def mensagem():
  print('Boa noite')


#Chamando a função
mensagem ()

#Função com parametros

def mensagem (nome):
  print('Boa noite ' +nome)

mensagem('Silvia')

def mensagem ():
  nomePessoa = input('Digite seu nome: ')
  print('Boa noite ' ,nomePessoa)


mensagem()

def calculoImc (peso, altura):
  print(peso/altura**2)

calculoImc(80, 1.70)

def calculoImc():
  peso = float(input('Peso: '))
  altura = float(input('Altura: '))

  imc = peso/altura**2

  print('IMC = ' ,imc)

  if imc < 18.5:
    print('Magreza')
  elif imc >= 18.5 and imc <= 24.9:
    print('Normal')
  elif imc >= 25 and imc <= 29.9:
    print('Sobrepeso')
  elif imc >= 30 and imc <= 34.9:
    print('Obesidade I')
  elif imc >= 35 and imc <= 39.9:
    print('Obesidade II')
  else:
    print('Obesidade III')


calculoImc()

def soma(x, y):
  total = x+y
  return total

print (soma( 100, 200))